version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install
          command: |
            yarn install
      - run:
          name: test
          command: |
            yarn test
      - run:
          name: build
          command: |
            yarn run build
